server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

minio:
  endpoint: https://localhost:9001
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: datasets 